### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke interface method 'void android.view.Window$Callback.onDetachedFromWindow()' on a null object reference com.uxcam.internals.ag.onDetachedFromWindow

### ISSUE THREAD

**Issue by developerashish01** [uxcam/cordova-uxcam#20]
I am having this issue on React Native app

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.Window$Callback.onDetachedFromWindow()' on a null object reference
       at com.uxcam.internals.ag.onDetachedFromWindow(:2)
       at com.android.internal.policy.DecorView.onDetachedFromWindow(DecorView.java:2274)
       at android.view.View.dispatchDetachedFromWindow(View.java:18537)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3818)
       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3903)
       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6947)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4278)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7099)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by developerashish01** [comment]
wrong place.
